/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/g7yo3lbOM8B
 */
import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { RadioGroupItem, RadioGroup } from "@/components/ui/radio-group"

interface Product {
  category_id: string;
  id: string;
  name: string;
  price: number;
  image_url: string;
} 

interface ProductListProps {
  products: Product[];
}

export function ProductList({ products }: ProductListProps) {
  return (
    <div key="1" className="flex flex-col min-h-screen">
      <header className="border-b">
        <div className="container flex items-center justify-between h-14 max-w-6xl px-4 sm:px-6">
          <nav className="flex items-center space-x-4">
            <Link className="font-bold" href="#">
              MallCo
            </Link>
            <div className="flex items-center space-x-4">
              <Link
                className="font-medium text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-50"
                href="#"
              >
                Women
              </Link>
              <Link
                className="font-medium text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-50"
                href="#"
              >
                Men
              </Link>
              <Link
                className="font-medium text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-50"
                href="#"
              >
                Kids
              </Link>
            </div>
          </nav>
          <form className="flex items-center space-x-2">
            <Label className="sr-only" htmlFor="search">
              Search
            </Label>
            <Input
              className="max-w-xs w-full sm:max-w-sm"
              id="search"
              placeholder="Search for products"
              type="search"
            />
            <Button size="sm" type="submit">
              Search
            </Button>
          </form>
        </div>
      </header>
      <main className="flex-1">
        <div className="grid lg:grid-cols-3 gap-4 max-w-6xl mx-auto px-4 py-8 sm:px-6 lg:gap-8 lg:px-8">
          <div className="lg:col-span-2 space-y-4">
            <form>
              <div className="grid items-center gap-4 md:grid-cols-2 lg:grid-cols-4">
                <div className="grid gap-0.5">
                  <Label className="text-sm font-medium [&:has(+*)]::before" htmlFor="category">
                    Category
                  </Label>
                  <div>
                    <div className="flex items-center gap-2 ml-2">
                      <Label
                        className="cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                        htmlFor="category-all"
                      >
                        <div />
                        All
                      </Label>
                      <Label
                        className="cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                        htmlFor="category-clothing"
                      >
                        <div />
                        T-shirts
                      </Label>
                      <Label
                        className="cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                        htmlFor="category-shoes"
                      >
                        <div />
                        Pants
                      </Label>
                      <Label
                        className="cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                        htmlFor="category-accessories"
                      >
                        <div />
                        Jacket
                      </Label>
                    </div>
                  </div>
                </div>
              </div>
            </form>
            <div className="grid items-start gap-4 md:grid-cols-2 lg:grid-cols-3">
              { products.map((product) => ( 
                <div key={product.id} className="grid items-start gap-2">
                  <Link className="flex items-start gap-4" href="#">
                    <img
                      alt={product.name}
                      className="aspect-square object-cover rounded-lg border border-gray-200 w-40 hover:border-gray-900 dark:border-gray-800 dark:hover:border-gray-50 dark:border-gray-800"
                      height={150}
                      src={product.image_url}
                      width={150}
                    />
                    <div className="grid items-start gap-1.5">
                      <h3 className="font-semibold text-base sm:text-xl md:text-base lg:text-xl xl:text-2xl">
                        {product.name}
                      </h3>
                      <p className="font-semibold text-base sm:text-xl md:text-base lg:text-xl xl:text-2xl">${product.price}</p>
                    </div>
                  </Link>
                </div>
              ))}
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
